### ISSUE TITLE
SyntaxError.backtrace_locations is nil

### ISSUE THREAD

**Issue by bemky** [malomalo/condenser#19]
```
Puma caught this error: undefined method `map' for nil:NilClass (NoMethodError)
/opt/homebrew/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/syntax_error_proxy.rb:41:in `backtrace_locations'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:274:in `build_backtrace'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:56:in `initialize'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:290:in `new'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:290:in `block in wrapped_causes_for'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:286:in `causes_for'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:290:in `each'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:290:in `map'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:290:in `wrapped_causes_for'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/exception_wrapper.rb:51:in `initialize'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/show_exceptions.rb:35:in `new'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/rack/logger.rb:37:in `call_app'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/rack/logger.rb:24:in `block in call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/tagged_logging.rb:135:in `block in tagged'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/tagged_logging.rb:39:in `tagged'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/tagged_logging.rb:135:in `tagged'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/broadcast_logger.rb:240:in `method_missing'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/rack/logger.rb:24:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/request_id.rb:28:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/runtime.rb:22:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/server_timing.rb:58:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.1.2/lib/action_dispatch/middleware/static.rb:25:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/engine.rb:529:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by malomalo** [comment]
Fixed in Rails 7.1.3 rails/rails#50764
